### ISSUE TITLE
Add support for finding Visual Studio 2017 installation

### ISSUE THREAD

**Issue by lewissbaker** [lewissbaker/cake#8]
The Cake build system up until now has relied on the registry to determine whether a particular Visual Studio version is installed and if so where it is installed.

With Visual Studio 2017 this has changed: https://blogs.msdn.microsoft.com/heaths/2016/09/15/changes-to-visual-studio-15-setup/

We need to add a new function to cake.library.compilers.msvc to find the installation path of VS 2017 using the new COM API.

**Comment by lewissbaker** [comment]
Seems to be some discussion of the changes here as well: https://developercommunity.visualstudio.com/content/problem/2813/cant-find-registry-entries-for-visual-studio-2017.html

**Comment by donno** [comment]
Alternatively, the new vswhere tool may be able to help with this:
https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/

**Comment by lewissbaker** [comment]
Added support for VS 2017 using vswhere.exe in ccb64fd82ea829cdda5f2053edccc70346c5125a
